### ISSUE TITLE
How to draw text "中文 cn zh font" (Hei.ttf:43KB) in nico

### ISSUE THREAD

**Issue by Angluca** [ftsf/nico#103]
Example all use draw english, Please tell me how to  use func draw  "中文字体" text . T^T

**Comment by Angluca** [comment]
https://takwolf.itch.io/ark-pixel-font
T^T I'm a newbie, Don't know how to generate font png data, Teach me pls .

**Comment by ftsf** [comment]
You need a 3 color png file with black characters (index 1) on transparent background (index 0), separated by white pixels (index 2).

The png.dat file should contain the list of characters (int UTF-8) in the same order that they appear in the png

**Comment by ftsf** [comment]
![image](https://user-images.githubusercontent.com/141492/230770549-84024713-2539-4efc-abaa-6a51f45a5545.png)

example of the png image format

**Comment by Angluca** [comment]
Is there a limit to increasing the size and length in font.data?
Maybe add more than a hundred characters to it ...

**Comment by ftsf** [comment]
It should be fine!
