### ISSUE TITLE
Official Nico logo?

### ISSUE THREAD

**Issue by matkuki** [ftsf/nico#107]
Does an official logo for `Nico` exist?
For adding it to apps for promotion: `Powered by Nico`

**Comment by Angluca** [comment]
@matkuki  It's in exampleApp or you nicoboot new project assets/icon.png
![icon](https://user-images.githubusercontent.com/156404/233165162-b1e04f7c-a2d7-431e-8fab-39a81fb7bac2.png)

**Comment by matkuki** [comment]
Excellent, thanks 👍👍
