### ISSUE TITLE
Add 32 bit palette support and get the spritesheet's colors

### ISSUE THREAD

**Issue by krisppurg** [ftsf/nico#12]
And put all of the spritesheet's colours to the palette and load it.

**Comment by ftsf** [comment]
Hi, I've got an update which adds 256 color (8 bit) palette support in the works. Ideally this would load the spritesheet's palette, however on web we can't read the palette from the image, only the colors from the image. But I'll add a command to load palette from image. Thanks.

**Comment by ftsf** [comment]
support for up to 256 color palettes is now in.

**Comment by krisppurg** [comment]
Fantastic.
