### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by dvska** [ftsf/nico#13]
/nico/backends/common.nim(323, 30) Error: type mismatch: got <ColorId> but expected 'uint8'

**Comment by dexelon** [comment]
It is fixed on the nim0.20.0 branch

**Comment by Minimisthupper** [comment]
> It is fixed on the nim0.20.0 branch so you can install the branch.

![Screen Shot 2020-04-13 at 17 17 23](https://user-images.githubusercontent.com/36794294/79132639-fcf44280-7daa-11ea-8b03-0476d7907a56.png)

am i doing anything wrong?

**Comment by krisppurg** [comment]
@Minimisthupper https://github.com/ftsf/nico/issues/11#issuecomment-614286941


Sorry to confuse you.

**Comment by ftsf** [comment]
it's been updated to work with new nim now, thanks.
