### ISSUE TITLE
Volume control does not seem to work.

### ISSUE THREAD

**Issue by beef331** [ftsf/nico#18]
Using `musicVol` and `masterVol` has no effect on the music volume, unless they're set to 0. Tested on Linux, current Master commit. Attached is a demo project that the error occurs in.
[TestProj.zip](https://github.com/ftsf/nico/files/4675053/TestProj.zip)

**Comment by ftsf** [comment]
Thanks, I'll look into it!

**Comment by ftsf** [comment]
Hi, looks like it works, however volume is between 0 and 255.
Here's your example code updated to allow you to adjust the volume with left and right buttons, you should be able to hear the volume change as you adjust the volume.

```nim
import nico

proc init() =
    music(0,2,0)
    musicVol(255)
    masterVol(255)

proc update(dt : Pfloat) =
  if btnpr(pcLeft):
    # adjust volume down
    var vol = musicVol()
    vol -= 10
    musicVol(vol)
  if btnpr(pcRight):
    # adjust volume up
    var vol = musicVol()
    vol += 10
    musicVol(vol)

proc draw() =
  cls()
  setColor(7)
  # draw music volume
  rectfill(1,1,(screenWidth-1).float32 * musicVol().float32 / 255.0f,4)

nico.init("BeefGame","Random Game")

nico.createWindow("nico",128,128,4,false)
loadMusic(0,"music.ogg")

nico.run(init,update,draw)
```

**Comment by beef331** [comment]
That example doesnt run properly either. Volume is at a constant 100%. I tried both system libraries, building sdl2 from source, and also using the Steam Runtime libraries. All have the same volume at 100% unless 0.

**Comment by ftsf** [comment]
@beef331 can you confirm which version of nim and nico you're using when this doesn't work?
the above example is working correctly for me with nim 1.2.0 and nico 0.2.1.

**Comment by beef331** [comment]
Those versions match the ones I'm running. Worth noting my entire system audio gets distorted when launching nico.

**Comment by ftsf** [comment]
@beef331  Very strange, which platform are you running this on? I've been testing on Windows 10.
Moving In is made with a very old version of Nico, so it's not directly comparable.

**Comment by beef331** [comment]
I've had this issue on Ubuntu and Regolith Linux 64bit.

**Comment by ftsf** [comment]
@beef331 ok, i'll do some testing on linux soon, thanks.

**Comment by geotre** [comment]
I'm also having audio issues, audio is completely distorted and very loud on the platformer and paint examples.

Ubuntu 18.04
Using sdl2 from the apt repos and sdl2 built from scratch
using libsndfile from apt repos and libsndfile built from scratch

Compiling and running a demo program included with the libsndfile source code does not have the same issue

**Comment by ftsf** [comment]
this should be fixed now! I was using the wrong sample format when opening the audio device. I dont know why it worked on windows.

**Comment by geotre** [comment]
Latest update fixed the audio for me :+1:
