### ISSUE TITLE
could not launch gui: `could not import: SDL_RWsize`

### ISSUE THREAD

**Issue by jiro4989** [ftsf/nico#21]
Hello. I tried `examples/platformer` of this repository.
https://github.com/ftsf/nico/blob/master/examples/platformer.nim

But I could not run this application.

My environment is here.

* OS: Ubuntu 18.04
* Nim: 1.2.2
* NImble: 0.11.4

```bash
$ nimble platformer
$ ./examples/platformer
could not import: SDL_RWsize
```

How can i run this?

**Comment by ftsf** [comment]
Hi, this error usually means it can't find libSDL2, on Linux you should be able to use your package manager to install it

**Comment by jiro4989** [comment]
hmm ...

I installed SDL2 packages.

```bash
$ sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev
```

```bash
$ find /usr/ -name '*.so' | grep -i libsdl2
/usr/lib/x86_64-linux-gnu/libSDL2_ttf.so
/usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2_image.so
/usr/lib/x86_64-linux-gnu/libSDL2_mixer.so
/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2.so
/usr/lib/x86_64-linux-gnu/libSDL2_net-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2_net.so
/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so
```

not enough?

**Comment by ftsf** [comment]
It's possible your version of SDL2 is too old, what version is installed? I think it needs to be at least 2.0.10

**Comment by jiro4989** [comment]
Thanks.
2.0.8 was installed.
I will upgrade libsdl2.

**Comment by jiro4989** [comment]
Thank you.

I upgraded OS (from Ubuntu 18.04 to 20.04)
and upgraded libsdl2-dev (from 2.0.8 to 2.0.10).

And I could run platformer example.
