### ISSUE TITLE
key/keyp etc do not handle arrow keys in JS backend

### ISSUE THREAD

**Issue by avahe-kellenberger** [ftsf/nico#25]
(Tested on Firefox and chromium): Normal keys work just fine, but nothing happens when arrow keys are pressed. The program I tested works natively (Linux)

**Comment by ftsf** [comment]
Hi, that's odd, I'm using arrow keys quite a lot in my testing on web, could you share the code you're using to test for input?

I'm using

```nim
if btnp(pcLeft):
  echo "left pressed"
if btnp(pcRight):
  echo "right pressed"
```

**Comment by avahe-kellenberger** [comment]
I was using key(K_LEFT) etc

**Comment by avahe-kellenberger** [comment]
Are you experiencing the same issue? For now I'll use btnp, though

**Comment by ftsf** [comment]
JS backend is now removed, using emscripten is now the way to build for web.
