### ISSUE TITLE
nico package not found

### ISSUE THREAD

**Issue by Acidic9** [ftsf/nico#3]
I've just installed nim on my Win10 x64 system and successfully made a helloworld.nim program.
I now tried installing nico with `nimble install nico` and got the following output:

```bash
$ nimble install nico --verbose
    Reading official package list
    Prompt: nico not found in any local packages.json, check internet for updated packages? [y/N]
    Answer: y
Downloading Official package list
     Trying https://github.com/nim-lang/packages/raw/master/packages.json
    Success Package list downloaded.
    Reading official package list
     Error: Package not found.
```

**Comment by dom96** [comment]
This should work now. I just added it to the Nimble package list (hope you don't mind @ftsf  :))

**Comment by dom96** [comment]
Btw, ProTip: you can use ``nimble develop nico`` to clone the repo into ``$CWD/nico`` and link it to Nimble, allowing you to access the examples and edit the nico code if necessary

**Comment by ftsf** [comment]
Cheers @dom96, was going to do that shortly, but now shouldn't hurt =)
