### ISSUE TITLE
Nico JS backend broken on Nim 1.4

### ISSUE THREAD

**Issue by ftsf** [ftsf/nico#36]
When compiling for JS backend we get the following error:

```C:\Users\user\.nimble\pkgs\ajax-0.1.0\ajax.nim(16, 3) Error: attempt to redefine: 'onloadstart'```

These are now defined in `dom` module as part of `EventTargetObj`

**Comment by ftsf** [comment]
Created issue in `ajax` module https://github.com/stisa/ajax/issues/1

**Comment by ftsf** [comment]
JS backend is now removed, using emscripten is now the way to build for web.

**Comment by pietroppeter** [comment]
ah that's a pity, I liked the fact that it was super easy to deploy on web! But I imagine it is a bit of a burden to maintain that in parallel...
