### ISSUE TITLE
SDL Calls

### ISSUE THREAD

**Issue by opselo** [ftsf/nico#42]
Sorry I couldn't find another way to communicate with you.

Hi, I am absolutely new to this. (in fact I haven't installed nim yet)

Using nico, could I make direct calls to SDL2?
Could for example (SDL_SetWindowOpacity) from nico, or how would this be done?
 Thanks for all your work.

**Comment by ftsf** [comment]
Hi there, yes it's certainly possible.

```nim
import nico
import sdl2/sdl

proc gameInit() =
  discard window.setWindowOpacity(0.5f)

```

However to get `window` you'd need to extend `nico.nim` and `nico/backends/sdl.nim` to expose the SDL `window` variable, as nico is designed to not expose any SDL specific things to make it easier to support other backends I haven't done this, but it's easy to modify to suit your own purposes.

**Comment by opselo** [comment]
Thanks, let's see what a Pascal dinosaur can do with this NicoNim. I guess as soon as any functionality is extended, the magic to export to the Web will be broken. But what better incentive to get your hands on a new language.
Really, thank you for your time.
