### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by opselo** [ftsf/nico#43]
I have downloaded the smalltrek, however I have been able to see a finalized and compiled game for distribution and something has caught my attention ...
All assets are exposed and I am wondering if this is the only way of distribution or nico or nim can compile resources within the executable ?

**Comment by ftsf** [comment]
Nico references assets via file path, you could if you wished for the SDL backend modify it to use something like physicsfs https://icculus.org/physfs/ which allows using a zip file for storing all your file assets.
