### ISSUE TITLE
SDL2 Versions

### ISSUE THREAD

**Issue by opselo** [ftsf/nico#44]
Is it possible to compile with an older version of SDL?

In GNU / Linux non-developer users usually do not have the latest versions of SDL installed (or they are missing from the repositories)

**Comment by SolitudeSF** [comment]
nim doesnt link to libraries at compile time, it finds and opens them at runtime.

**Comment by opselo** [comment]
Okay I understand. It all comes from this error: "could not import: SDL_RWsize
". Another user commented on how to fix this with LD_LIBRARY_PATH. Unfortunately for me with (Debian 10 64) it didn't work. I even manually made symbolic links to 0.12 and 0.14.

Could I somehow bypass this call? I installed nim and nico for the first time today. It was nice how the compilation to the web worked the first time, but frustrating not being able to run any example (or itchio nico game) for this error.

**Comment by SolitudeSF** [comment]
2.0.10 is required which is already 1.5 years old. if there is absolutely no way the you can use actually relevant version, you install and locally patch the bindings https://github.com/Vladar4/sdl2_nim/blob/216414283b671c8b65f2b1444a0b1ee2671fc9b5/sdl2/private/rwops.nim#L158 uncomment the templates and comment relevant procs.

**Comment by opselo** [comment]
Thanks @SolitudeSF 
I aplied te patch. Works like a charm.
Now I see a high effort by my cpu with the hello world sample (1 Core=100%). I dont know if this is by the applied patch, or a normal behaviour of Nico. Normally when I play with the SDL2 Pascal bindings, CPU is about 8%  even with software render (on hello world).

**Comment by SolitudeSF** [comment]
you can try running examples from sdl bindings to rule out nico.

**Comment by opselo** [comment]
Compiling init.nim (SDL but not Nico):  
cpu is about 12%~14%

I can't compile the rest of examples  for errors like "could not load: libSDL2_image(|-2.0).so(|.0.2.3|.0)". I suposse ... maybe i must pass parameters to compiler, but is my first hours with nim.

Anyway, seems that SDL bindings work perfect.

**Comment by SolitudeSF** [comment]
you need SDL2-image, which is distributed separately

**Comment by SolitudeSF** [comment]
and cpu usage is #23

**Comment by ftsf** [comment]
I've pushed a potential fix for the CPU usage on Linux. Let me know if that helps.

As for SDL version, I'd recommend doing what most games do and ship a shared library with your application and include a script to run your executable with a modified library path to include your bundled libraries before system ones.
