### ISSUE TITLE
Error: unhandled exception: index out of bounds [IndexError]

### ISSUE THREAD

**Issue by ghost** [ftsf/nico#5]
If binaries are compiled in debug mode, then at runtime -
```
main.nim(175)            main
nico.nim(1539)           init
nico.nim(1141)           loadFont
sdl2.nim(349)            loadSurface
nico.nim(1143)           :anonymous
nico.nim(1128)           createFontFromSurface
system.nim(2811)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

**Comment by allochi** [comment]
file `nico.nim`, procedure `createFontFromSurface()`, line 1127, it would work if the `for` loop change to:

```nim
for y in 0..font.h-1:
```

I didn't have the time to read the function and full understand how it slices the png file, but the line before identify the current rectangle to be:

```nim
currentRect.h = font.h-1
```

besides the sequence `font.data` is declared as

```nim
font.data = newSeq[uint8](font.w*font.h)
```

Therefore, the upper bound in the `y` direction for `font.data` should be font.h-1.

This library is really nice and fun to use. Thanks a lot!

**Comment by ftsf** [comment]
Thanks for finding this, this is fixed now. Sorry I didn't see these notifications for some reason =\
