### ISSUE TITLE
JS backend doesn't respect integerScale(false)

### ISSUE THREAD

**Issue by jorisbontje** [ftsf/nico#50]
The JS backend will always do integer scaling of the canvas, even if it is disabled via `integerScale(false)`
Expected is that it will allow for more continuous scaling when this is disabled. This is important to handle mobile devices in a responsive way.

The offending code:
https://github.com/ftsf/nico/blob/master/nico/backends/js.nim#L570

**Comment by ftsf** [comment]
I did some more testing with a new example and it didn't seem like integerScale(false) was working still, but it does now. You can test out screenscale.nim in examples.
