### ISSUE TITLE
attempting to save/load/update config on JS backend when cookies are disabled throws a DOMException

### ISSUE THREAD

**Issue by beef331** [ftsf/nico#53]
If the localstorage api is blocked or otherwise unaccessible attempting to save will result in a nil reference error.

**Comment by ftsf** [comment]
@beef331 could you provide a way that I can reproduce this issue, also the error and a full stacktrace would be useful.

**Comment by beef331** [comment]
Looking into it further disabling cookies on a webpage and running this code will result in the error.
```nim
import nico
updateConfigValue("data", "test", "11222")
saveConfig()
echo "Hmm"
```

**Comment by ftsf** [comment]
would recommend just wrapping in a `try` block and catching the Exception and showing a message if appropriate.
