### ISSUE TITLE
Problems with fresh install on Nim 1.5.1?

### ISSUE THREAD

**Issue by madasebrof** [ftsf/nico#64]
Hey! Just playing around with Nim & Nico, but when I tried to make a sample app using `nicoboot`, I get an error:

```
C:\Users\Foo\.nimble\pkgs\nico-0.3.2\nico\backends\sdl2.nim(21, 19) Error: type mismatch:
 got 'Keycode' for 'x' [enum declared in C:\Users\Foo\.nimble\pkgs\sdl2-2.0.12.0\sdl2\private\keycode.nim(34, 3)]
 but expected 'Keycode = enum' [enum declared in C:\Users\Foo\.nimble\pkgs\nico-0.3.2\nico\keycodes.nim(207, 3)]
maybe use `-d:nimLegacyConvEnumEnum` for a transition period
```

When I add the `-d:nimLegacyConvEnumEnum` flag, I then get 

```
Error: ambiguous identifier: 'SCANCODE_LEFT' -- use one of the following:
  Scancode.SCANCODE_LEFT: Scancode
  Scancode.SCANCODE_LEFT: Scancode
```

I am using the last Nim from GitHub, as the installers are triggering a virus alert. It looks like I had built Nim 1.5.1.

(I guess Nim doesn't have semantic versioning, as that seems to have broken Nico...)

Okay, just re-compiled from source with version 1.4.8, works great!

(ps just for others, you have to delete `*.exe` from `Nim/bin` otherwise `build_all.bat` doesn't recompile Nim itself!)

**Comment by pyautogui** [comment]
Same here. Even with the same error.

**Comment by ftsf** [comment]
I haven't looked into Nim > 1.4 yet, I wasn't aware there was a 1.5 yet.
I'll see what I can do to get it working with those, but for now it's designed for 1.4.x

**Comment by ftsf** [comment]
Seems like this may be related to #49

**Comment by ftsf** [comment]
1.5 and 1.6 are now supported
