### ISSUE TITLE
undeclared identifier: 'queueMixerAudio'

### ISSUE THREAD

**Issue by Feinbube** [ftsf/nico#7]
First of all, thanks for your awesome project :)

I tried to build the examples (on Windows and Ubuntu) using `nimble examples`.

In both cases, I only got:
`sdl2.nim(728, 9) Error: undeclared identifier: 'queueMixerAudio'`

Any ideas what I can do make it work?

**Comment by nc-x** [comment]
In `nico/backends/sdl2.nim`, `queueMixerAudio` is missing a forward declaration. Till the time it is fixed here, you can manually do the required change in your local copy of `nico` that you got when you did `nimble install nico`.

**Comment by ftsf** [comment]
This is now resolved. Thanks.
