### ISSUE TITLE
LCT_RGB .png files never loaded.

### ISSUE THREAD

**Issue by kinesivan** [ftsf/nico#84]
On macOS 11.1 with latest master build, .png files with LCT_RGB type never get displayed (or used, seemingly) when loading them as spritesheets. Only LCT_RGBA is accepted. Maybe this is an issue caused with how I'm exporting the .png?

LCT_RGB ignored:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3822492/154874246-e3d64be2-6a20-4911-820d-2751b4de6b2c.png">

LCT_RGBA accepted:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/3822492/154874191-2b3802e9-91d4-4af5-9fa8-6fafed4c8c4d.png">

**Comment by ftsf** [comment]
Yep, I can confirm this is an issue, I'll fix it, but I would suggest you use either paletted spritesheets or RGBA spritesheets for since color 0 is transparent.
